### ISSUE TITLE
repo.boundlessgeo.com has closed

### ISSUE THREAD

**Issue by GrantSparks** [codebrewer/dump1090-processor#9]
Currently the build fails with the following.

> Could not resolve org.opengeo:geodb:0.9.
         > Could not get resource 'https://repo.boundlessgeo.com/main/org/opengeo/geodb/0.9/geodb-0.9.pom'.
            > Could not GET 'https://repo.boundlessgeo.com/main/org/opengeo/geodb/0.9/geodb-0.9.pom'.
               > repo.boundlessgeo.com

The problem is that repo is no longer available.

See  https://support.planet.com/hc/en-us/community/posts/360009782998-repo-boundlessgeo-com-is-unavailable-

**Comment by codebrewer** [comment]
Thanks for the report. I found another repo that hosts the `org.opengeo:geodb` artifacts and have pushed the change to `develop` (I managed to refer to the wrong issue in the commit message though so it won't show up against this one...).

I should say that _this_ project has languished too - it didn't have a clear goal at the outset and one hasn't emerged (not helped by the pandemic removing my commute-time hacking opportunities ☹️).
